externalHost: qa.serval-api.org
environment: Production
deploymentVersion: '1.14.0-rc.1'
alertEmail: ext-qa-serval-alerts@languagetechnology.org
emailsToAlert: eli_lowry@sil.org
enableTls: true
namespace: serval
auth0Domain: dev-sillsdev.auth0.com
lokiTenant: serval-tenant
lokiUrl: http://loki-distributed-gateway.loki.svc.cluster.local
servalImage: ghcr.io/sillsdev/serval:1.14.0-rc.1
ClearMLDockerImage: ghcr.io/sillsdev/machine.py:1.11.0
ClearMLQueue: production
MongoConnectionPrefix: qa_
SharedFileLocation: s3://silnlp/ext-qa/
servalClaimSize: 11Gi
machineClaimSize: 25Gi
enableEcho: true