externalHost: prod.serval-api.org
environment: Production
deploymentVersion: '1.12.1'
alertEmail: prod-serval-alerts@languagetechnology.org
emailsToAlert: eli_lowry@sil.org
enableTls: true
namespace: serval
auth0Domain: languagetechnology.auth0.com
lokiTenant: nlp-tenant
lokiUrl: http://loki-distributed-gateway.loki.svc.cluster.local
servalImage: ghcr.io/sillsdev/serval:1.12.1
ClearMLDockerImage: ghcr.io/sillsdev/machine.py:1.10.0
ClearMLQueue: production
MongoConnectionPrefix: prod_
SharedFileLocation: s3://silnlp/production/
servalClaimSize: 15Gi
machineClaimSize: 100Gi
enableEcho: true